project_name: nostos
builds:
  - main: .
    binary: nostos
    ldflags:
      - -X=cmd.gitVersion={{ .ShortCommit }}
archives:
  - format: tar.gz
    files:
      - README.md

release:
  github:
    owner: wycleffsean
    name: nostos

