// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[itemError-0]
	_ = x[itemDot-1]
	_ = x[itemDocStart-2]
	_ = x[itemDocEnd-3]
	_ = x[itemEOF-4]
	_ = x[itemList-5]
	_ = x[itemColon-6]
	_ = x[itemNumber-7]
	_ = x[itemString-8]
}

const _itemType_name = "itemErroritemDotitemDocStartitemDocEnditemEOFitemListitemColonitemNumberitemString"

var _itemType_index = [...]uint8{0, 9, 16, 28, 38, 45, 53, 62, 72, 82}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
